// Code generated by protoc-gen-go. DO NOT EDIT.
// source: upload.proto

//protoc.exe --proto_path=common/rpcinterface/uploadinterface --go_out=common/rpcinterface/uploadinterface --micro_out=common/rpcinterface/uploadinterface common/rpcinterface/uploadinterface/upload.proto

package uploadinterface

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadEndPointReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadEndPointReq) Reset()         { *m = UploadEndPointReq{} }
func (m *UploadEndPointReq) String() string { return proto.CompactTextString(m) }
func (*UploadEndPointReq) ProtoMessage()    {}
func (*UploadEndPointReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{0}
}

func (m *UploadEndPointReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadEndPointReq.Unmarshal(m, b)
}
func (m *UploadEndPointReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadEndPointReq.Marshal(b, m, deterministic)
}
func (m *UploadEndPointReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadEndPointReq.Merge(m, src)
}
func (m *UploadEndPointReq) XXX_Size() int {
	return xxx_messageInfo_UploadEndPointReq.Size(m)
}
func (m *UploadEndPointReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadEndPointReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadEndPointReq proto.InternalMessageInfo

type UploadEndPointResp struct {
	Code                 int64                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *UploadEndPointResp_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *UploadEndPointResp) Reset()         { *m = UploadEndPointResp{} }
func (m *UploadEndPointResp) String() string { return proto.CompactTextString(m) }
func (*UploadEndPointResp) ProtoMessage()    {}
func (*UploadEndPointResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{1}
}

func (m *UploadEndPointResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadEndPointResp.Unmarshal(m, b)
}
func (m *UploadEndPointResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadEndPointResp.Marshal(b, m, deterministic)
}
func (m *UploadEndPointResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadEndPointResp.Merge(m, src)
}
func (m *UploadEndPointResp) XXX_Size() int {
	return xxx_messageInfo_UploadEndPointResp.Size(m)
}
func (m *UploadEndPointResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadEndPointResp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadEndPointResp proto.InternalMessageInfo

func (m *UploadEndPointResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UploadEndPointResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UploadEndPointResp) GetData() *UploadEndPointResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadEndPointResp_Data struct {
	Endpoint             string   `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadEndPointResp_Data) Reset()         { *m = UploadEndPointResp_Data{} }
func (m *UploadEndPointResp_Data) String() string { return proto.CompactTextString(m) }
func (*UploadEndPointResp_Data) ProtoMessage()    {}
func (*UploadEndPointResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{1, 0}
}

func (m *UploadEndPointResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadEndPointResp_Data.Unmarshal(m, b)
}
func (m *UploadEndPointResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadEndPointResp_Data.Marshal(b, m, deterministic)
}
func (m *UploadEndPointResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadEndPointResp_Data.Merge(m, src)
}
func (m *UploadEndPointResp_Data) XXX_Size() int {
	return xxx_messageInfo_UploadEndPointResp_Data.Size(m)
}
func (m *UploadEndPointResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadEndPointResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_UploadEndPointResp_Data proto.InternalMessageInfo

func (m *UploadEndPointResp_Data) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*UploadEndPointReq)(nil), "uploadinterface.UploadEndPointReq")
	proto.RegisterType((*UploadEndPointResp)(nil), "uploadinterface.UploadEndPointResp")
	proto.RegisterType((*UploadEndPointResp_Data)(nil), "uploadinterface.UploadEndPointResp.Data")
}

func init() { proto.RegisterFile("upload.proto", fileDescriptor_91b94b655bd2a7e5) }

var fileDescriptor_91b94b655bd2a7e5 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2d, 0xc8, 0xc9,
	0x4f, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x87, 0xf0, 0x32, 0xf3, 0x4a, 0x52,
	0x8b, 0xd2, 0x12, 0x93, 0x53, 0x95, 0x84, 0xb9, 0x04, 0x43, 0xc1, 0x42, 0xae, 0x79, 0x29, 0x01,
	0xf9, 0x99, 0x79, 0x25, 0x41, 0xa9, 0x85, 0x4a, 0x4b, 0x18, 0xb9, 0x84, 0xd0, 0x45, 0x8b, 0x0b,
	0x84, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0xc0,
	0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x18, 0x57, 0xc8, 0x86, 0x8b, 0x25, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x59, 0x81,
	0x51, 0x83, 0xdb, 0x48, 0x43, 0x0f, 0xcd, 0x66, 0x3d, 0x4c, 0x0b, 0xf4, 0x5c, 0x12, 0x4b, 0x12,
	0x83, 0xc0, 0xba, 0xa4, 0x94, 0xb8, 0x58, 0x40, 0x3c, 0x21, 0x29, 0x2e, 0x8e, 0xd4, 0xbc, 0x94,
	0x02, 0x90, 0x12, 0xb0, 0x49, 0x9c, 0x41, 0x70, 0xbe, 0x51, 0x16, 0x17, 0x2f, 0xc4, 0x90, 0xe0,
	0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0xa1, 0x48, 0x2e, 0x3e, 0x54, 0x53, 0x85, 0x94, 0x08, 0x5a,
	0x5b, 0x28, 0xa5, 0x4c, 0x84, 0xd3, 0x92, 0xd8, 0xc0, 0xe1, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x77, 0x49, 0x9c, 0x31, 0x4f, 0x01, 0x00, 0x00,
}
