// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: upload.proto

//protoc.exe --proto_path=common/rpcinterface/uploadinterface --go_out=common/rpcinterface/uploadinterface --micro_out=common/rpcinterface/uploadinterface common/rpcinterface/uploadinterface/upload.proto

package uploadinterface

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UploadService service

type UploadService interface {
	UploadEndPoint(ctx context.Context, in *UploadEndPointReq, opts ...client.CallOption) (*UploadEndPointResp, error)
}

type uploadService struct {
	c    client.Client
	name string
}

func NewUploadService(name string, c client.Client) UploadService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "uploadinterface"
	}
	return &uploadService{
		c:    c,
		name: name,
	}
}

func (c *uploadService) UploadEndPoint(ctx context.Context, in *UploadEndPointReq, opts ...client.CallOption) (*UploadEndPointResp, error) {
	req := c.c.NewRequest(c.name, "UploadService.UploadEndPoint", in)
	out := new(UploadEndPointResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UploadService service

type UploadServiceHandler interface {
	UploadEndPoint(context.Context, *UploadEndPointReq, *UploadEndPointResp) error
}

func RegisterUploadServiceHandler(s server.Server, hdlr UploadServiceHandler, opts ...server.HandlerOption) error {
	type uploadService interface {
		UploadEndPoint(ctx context.Context, in *UploadEndPointReq, out *UploadEndPointResp) error
	}
	type UploadService struct {
		uploadService
	}
	h := &uploadServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UploadService{h}, opts...))
}

type uploadServiceHandler struct {
	UploadServiceHandler
}

func (h *uploadServiceHandler) UploadEndPoint(ctx context.Context, in *UploadEndPointReq, out *UploadEndPointResp) error {
	return h.UploadServiceHandler.UploadEndPoint(ctx, in, out)
}
