// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: download.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DownloadService service

type DownloadService interface {
	DownloadEndPoint(ctx context.Context, in *DownloadEndpointReq, opts ...client.CallOption) (*DownloadEndpointResp, error)
}

type downloadService struct {
	c    client.Client
	name string
}

func NewDownloadService(name string, c client.Client) DownloadService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &downloadService{
		c:    c,
		name: name,
	}
}

func (c *downloadService) DownloadEndPoint(ctx context.Context, in *DownloadEndpointReq, opts ...client.CallOption) (*DownloadEndpointResp, error) {
	req := c.c.NewRequest(c.name, "DownloadService.DownloadEndPoint", in)
	out := new(DownloadEndpointResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DownloadService service

type DownloadServiceHandler interface {
	DownloadEndPoint(context.Context, *DownloadEndpointReq, *DownloadEndpointResp) error
}

func RegisterDownloadServiceHandler(s server.Server, hdlr DownloadServiceHandler, opts ...server.HandlerOption) error {
	type downloadService interface {
		DownloadEndPoint(ctx context.Context, in *DownloadEndpointReq, out *DownloadEndpointResp) error
	}
	type DownloadService struct {
		downloadService
	}
	h := &downloadServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DownloadService{h}, opts...))
}

type downloadServiceHandler struct {
	DownloadServiceHandler
}

func (h *downloadServiceHandler) DownloadEndPoint(ctx context.Context, in *DownloadEndpointReq, out *DownloadEndpointResp) error {
	return h.DownloadServiceHandler.DownloadEndPoint(ctx, in, out)
}
