// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package fileinterface

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetFileMetaReq struct {
	FileHash             string   `protobuf:"bytes,1,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileMetaReq) Reset()         { *m = GetFileMetaReq{} }
func (m *GetFileMetaReq) String() string { return proto.CompactTextString(m) }
func (*GetFileMetaReq) ProtoMessage()    {}
func (*GetFileMetaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *GetFileMetaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileMetaReq.Unmarshal(m, b)
}
func (m *GetFileMetaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileMetaReq.Marshal(b, m, deterministic)
}
func (m *GetFileMetaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileMetaReq.Merge(m, src)
}
func (m *GetFileMetaReq) XXX_Size() int {
	return xxx_messageInfo_GetFileMetaReq.Size(m)
}
func (m *GetFileMetaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileMetaReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileMetaReq proto.InternalMessageInfo

func (m *GetFileMetaReq) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

type GetFileMetaResp struct {
	Code                 int64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *GetFileMetaResp_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetFileMetaResp) Reset()         { *m = GetFileMetaResp{} }
func (m *GetFileMetaResp) String() string { return proto.CompactTextString(m) }
func (*GetFileMetaResp) ProtoMessage()    {}
func (*GetFileMetaResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1}
}

func (m *GetFileMetaResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileMetaResp.Unmarshal(m, b)
}
func (m *GetFileMetaResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileMetaResp.Marshal(b, m, deterministic)
}
func (m *GetFileMetaResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileMetaResp.Merge(m, src)
}
func (m *GetFileMetaResp) XXX_Size() int {
	return xxx_messageInfo_GetFileMetaResp.Size(m)
}
func (m *GetFileMetaResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileMetaResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileMetaResp proto.InternalMessageInfo

func (m *GetFileMetaResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetFileMetaResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetFileMetaResp) GetData() *GetFileMetaResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetFileMetaResp_Data struct {
	FileSha1             string   `protobuf:"bytes,1,opt,name=fileSha1,proto3" json:"fileSha1,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize             int64    `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	Location             string   `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	UploadAt             string   `protobuf:"bytes,5,opt,name=uploadAt,proto3" json:"uploadAt,omitempty"`
	UpdateAt             string   `protobuf:"bytes,6,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	Status               int64    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileMetaResp_Data) Reset()         { *m = GetFileMetaResp_Data{} }
func (m *GetFileMetaResp_Data) String() string { return proto.CompactTextString(m) }
func (*GetFileMetaResp_Data) ProtoMessage()    {}
func (*GetFileMetaResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1, 0}
}

func (m *GetFileMetaResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileMetaResp_Data.Unmarshal(m, b)
}
func (m *GetFileMetaResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileMetaResp_Data.Marshal(b, m, deterministic)
}
func (m *GetFileMetaResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileMetaResp_Data.Merge(m, src)
}
func (m *GetFileMetaResp_Data) XXX_Size() int {
	return xxx_messageInfo_GetFileMetaResp_Data.Size(m)
}
func (m *GetFileMetaResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileMetaResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileMetaResp_Data proto.InternalMessageInfo

func (m *GetFileMetaResp_Data) GetFileSha1() string {
	if m != nil {
		return m.FileSha1
	}
	return ""
}

func (m *GetFileMetaResp_Data) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *GetFileMetaResp_Data) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *GetFileMetaResp_Data) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *GetFileMetaResp_Data) GetUploadAt() string {
	if m != nil {
		return m.UploadAt
	}
	return ""
}

func (m *GetFileMetaResp_Data) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *GetFileMetaResp_Data) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type UpdateFileMetaReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FileHash             string   `protobuf:"bytes,2,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	Filename             string   `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Status               int64    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileMetaReq) Reset()         { *m = UpdateFileMetaReq{} }
func (m *UpdateFileMetaReq) String() string { return proto.CompactTextString(m) }
func (*UpdateFileMetaReq) ProtoMessage()    {}
func (*UpdateFileMetaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{2}
}

func (m *UpdateFileMetaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileMetaReq.Unmarshal(m, b)
}
func (m *UpdateFileMetaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileMetaReq.Marshal(b, m, deterministic)
}
func (m *UpdateFileMetaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileMetaReq.Merge(m, src)
}
func (m *UpdateFileMetaReq) XXX_Size() int {
	return xxx_messageInfo_UpdateFileMetaReq.Size(m)
}
func (m *UpdateFileMetaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileMetaReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileMetaReq proto.InternalMessageInfo

func (m *UpdateFileMetaReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateFileMetaReq) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *UpdateFileMetaReq) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *UpdateFileMetaReq) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type UpdateFileMetaResp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileMetaResp) Reset()         { *m = UpdateFileMetaResp{} }
func (m *UpdateFileMetaResp) String() string { return proto.CompactTextString(m) }
func (*UpdateFileMetaResp) ProtoMessage()    {}
func (*UpdateFileMetaResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{3}
}

func (m *UpdateFileMetaResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileMetaResp.Unmarshal(m, b)
}
func (m *UpdateFileMetaResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileMetaResp.Marshal(b, m, deterministic)
}
func (m *UpdateFileMetaResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileMetaResp.Merge(m, src)
}
func (m *UpdateFileMetaResp) XXX_Size() int {
	return xxx_messageInfo_UpdateFileMetaResp.Size(m)
}
func (m *UpdateFileMetaResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileMetaResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileMetaResp proto.InternalMessageInfo

func (m *UpdateFileMetaResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateFileMetaResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetFileListReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileListReq) Reset()         { *m = GetFileListReq{} }
func (m *GetFileListReq) String() string { return proto.CompactTextString(m) }
func (*GetFileListReq) ProtoMessage()    {}
func (*GetFileListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{4}
}

func (m *GetFileListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileListReq.Unmarshal(m, b)
}
func (m *GetFileListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileListReq.Marshal(b, m, deterministic)
}
func (m *GetFileListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileListReq.Merge(m, src)
}
func (m *GetFileListReq) XXX_Size() int {
	return xxx_messageInfo_GetFileListReq.Size(m)
}
func (m *GetFileListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileListReq proto.InternalMessageInfo

func (m *GetFileListReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetFileListReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetFileListResp struct {
	Code                 int64                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DataList             []*GetFileListResp_Data `protobuf:"bytes,3,rep,name=dataList,proto3" json:"dataList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetFileListResp) Reset()         { *m = GetFileListResp{} }
func (m *GetFileListResp) String() string { return proto.CompactTextString(m) }
func (*GetFileListResp) ProtoMessage()    {}
func (*GetFileListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{5}
}

func (m *GetFileListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileListResp.Unmarshal(m, b)
}
func (m *GetFileListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileListResp.Marshal(b, m, deterministic)
}
func (m *GetFileListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileListResp.Merge(m, src)
}
func (m *GetFileListResp) XXX_Size() int {
	return xxx_messageInfo_GetFileListResp.Size(m)
}
func (m *GetFileListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileListResp proto.InternalMessageInfo

func (m *GetFileListResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetFileListResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetFileListResp) GetDataList() []*GetFileListResp_Data {
	if m != nil {
		return m.DataList
	}
	return nil
}

type GetFileListResp_Data struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	FileHash             string   `protobuf:"bytes,3,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	FileSize             int64    `protobuf:"varint,4,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	UploadAt             string   `protobuf:"bytes,5,opt,name=uploadAt,proto3" json:"uploadAt,omitempty"`
	LastUpdate           string   `protobuf:"bytes,6,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileListResp_Data) Reset()         { *m = GetFileListResp_Data{} }
func (m *GetFileListResp_Data) String() string { return proto.CompactTextString(m) }
func (*GetFileListResp_Data) ProtoMessage()    {}
func (*GetFileListResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{5, 0}
}

func (m *GetFileListResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileListResp_Data.Unmarshal(m, b)
}
func (m *GetFileListResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileListResp_Data.Marshal(b, m, deterministic)
}
func (m *GetFileListResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileListResp_Data.Merge(m, src)
}
func (m *GetFileListResp_Data) XXX_Size() int {
	return xxx_messageInfo_GetFileListResp_Data.Size(m)
}
func (m *GetFileListResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileListResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileListResp_Data proto.InternalMessageInfo

func (m *GetFileListResp_Data) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetFileListResp_Data) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *GetFileListResp_Data) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *GetFileListResp_Data) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *GetFileListResp_Data) GetUploadAt() string {
	if m != nil {
		return m.UploadAt
	}
	return ""
}

func (m *GetFileListResp_Data) GetLastUpdate() string {
	if m != nil {
		return m.LastUpdate
	}
	return ""
}

type DeleteFileReq struct {
	FileHash             string   `protobuf:"bytes,1,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileReq) Reset()         { *m = DeleteFileReq{} }
func (m *DeleteFileReq) String() string { return proto.CompactTextString(m) }
func (*DeleteFileReq) ProtoMessage()    {}
func (*DeleteFileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{6}
}

func (m *DeleteFileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileReq.Unmarshal(m, b)
}
func (m *DeleteFileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileReq.Marshal(b, m, deterministic)
}
func (m *DeleteFileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileReq.Merge(m, src)
}
func (m *DeleteFileReq) XXX_Size() int {
	return xxx_messageInfo_DeleteFileReq.Size(m)
}
func (m *DeleteFileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileReq proto.InternalMessageInfo

func (m *DeleteFileReq) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

type DeleteFileResp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResp) Reset()         { *m = DeleteFileResp{} }
func (m *DeleteFileResp) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResp) ProtoMessage()    {}
func (*DeleteFileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{7}
}

func (m *DeleteFileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResp.Unmarshal(m, b)
}
func (m *DeleteFileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResp.Marshal(b, m, deterministic)
}
func (m *DeleteFileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResp.Merge(m, src)
}
func (m *DeleteFileResp) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResp.Size(m)
}
func (m *DeleteFileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResp proto.InternalMessageInfo

func (m *DeleteFileResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteFileResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetFileMetaReq)(nil), "fileinterface.GetFileMetaReq")
	proto.RegisterType((*GetFileMetaResp)(nil), "fileinterface.GetFileMetaResp")
	proto.RegisterType((*GetFileMetaResp_Data)(nil), "fileinterface.GetFileMetaResp.Data")
	proto.RegisterType((*UpdateFileMetaReq)(nil), "fileinterface.UpdateFileMetaReq")
	proto.RegisterType((*UpdateFileMetaResp)(nil), "fileinterface.UpdateFileMetaResp")
	proto.RegisterType((*GetFileListReq)(nil), "fileinterface.GetFileListReq")
	proto.RegisterType((*GetFileListResp)(nil), "fileinterface.GetFileListResp")
	proto.RegisterType((*GetFileListResp_Data)(nil), "fileinterface.GetFileListResp.Data")
	proto.RegisterType((*DeleteFileReq)(nil), "fileinterface.DeleteFileReq")
	proto.RegisterType((*DeleteFileResp)(nil), "fileinterface.DeleteFileResp")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0xb2, 0x6e, 0x5a, 0x26, 0x6a, 0x10, 0x2b, 0x84, 0x56, 0x16, 0xad, 0x82, 0xb9, 0x54,
	0x02, 0x59, 0xa2, 0x1c, 0xb8, 0x81, 0x5a, 0x55, 0xfc, 0x48, 0xe5, 0xe2, 0xaa, 0x0f, 0xb0, 0xd8,
	0x53, 0xba, 0x92, 0x13, 0xbb, 0xde, 0x0d, 0x07, 0x2e, 0xbc, 0x13, 0x12, 0x0f, 0xc0, 0x85, 0x0b,
	0x2f, 0x85, 0x76, 0xd7, 0xeb, 0x78, 0x5d, 0x6c, 0x2b, 0x37, 0x7f, 0x99, 0x9f, 0xfd, 0x66, 0xbe,
	0x6f, 0x02, 0x70, 0x23, 0x72, 0x8c, 0xcb, 0xaa, 0x50, 0x05, 0x3d, 0xd4, 0xdf, 0x62, 0xad, 0xb0,
	0xba, 0xe1, 0x29, 0x46, 0x2f, 0x61, 0xf1, 0x01, 0xd5, 0x7b, 0x91, 0xe3, 0x67, 0x54, 0x3c, 0xc1,
	0x3b, 0x1a, 0xc2, 0x81, 0x4e, 0xf9, 0xc8, 0xe5, 0x2d, 0x9b, 0x2c, 0x27, 0x27, 0x0f, 0x92, 0x06,
	0x47, 0xbf, 0xa7, 0xf0, 0xd0, 0x4b, 0x97, 0x25, 0xa5, 0x10, 0xa4, 0x45, 0x86, 0x26, 0x97, 0x24,
	0xe6, 0x9b, 0x32, 0xd8, 0x5f, 0xa1, 0x94, 0xfc, 0x2b, 0xb2, 0xa9, 0x69, 0xe1, 0x20, 0x7d, 0x03,
	0x41, 0xc6, 0x15, 0x67, 0x64, 0x39, 0x39, 0x99, 0x9f, 0x3e, 0x8f, 0x3d, 0x36, 0x71, 0xa7, 0x77,
	0x7c, 0xc1, 0x15, 0x4f, 0x4c, 0x41, 0xf8, 0x67, 0x02, 0x81, 0x86, 0x8e, 0xdf, 0xd5, 0x2d, 0x7f,
	0xd5, 0xe6, 0xa7, 0xb1, 0x8b, 0xad, 0xf9, 0xca, 0x3d, 0xdc, 0xe0, 0xa6, 0x4e, 0x7c, 0x47, 0xf3,
	0x3a, 0x49, 0x1a, 0xac, 0x63, 0x79, 0x91, 0x72, 0x25, 0x8a, 0x35, 0x0b, 0x6c, 0x9d, 0xc3, 0x3a,
	0xb6, 0x29, 0xf3, 0x82, 0x67, 0x67, 0x8a, 0xed, 0xd9, 0x98, 0xc3, 0x36, 0x96, 0x71, 0x85, 0x67,
	0x8a, 0xcd, 0x5c, 0xcc, 0x62, 0xfa, 0x04, 0x66, 0x52, 0x71, 0xb5, 0x91, 0x6c, 0xdf, 0xbc, 0x56,
	0xa3, 0xe8, 0x07, 0x3c, 0xba, 0x36, 0x39, 0x9d, 0xa5, 0x6f, 0x24, 0x56, 0x86, 0x78, 0x3d, 0x94,
	0xc3, 0x9e, 0x20, 0x53, 0x5f, 0x10, 0x6f, 0x60, 0xd2, 0x19, 0x78, 0x4b, 0x20, 0xf0, 0x08, 0x9c,
	0x03, 0xed, 0x12, 0xd8, 0x55, 0xc6, 0xe8, 0xbc, 0xb1, 0xcd, 0xa5, 0x90, 0x6a, 0x6c, 0x82, 0xc7,
	0xb0, 0x97, 0x8b, 0x95, 0x50, 0xa6, 0x0b, 0x49, 0x2c, 0x88, 0x7e, 0x6d, 0xcd, 0x64, 0x9b, 0xec,
	0x6c, 0xa6, 0x77, 0x70, 0xa0, 0xbd, 0xa1, 0xab, 0x19, 0x59, 0x92, 0x7e, 0x43, 0xb9, 0xfe, 0xd6,
	0x50, 0x4d, 0x51, 0xf8, 0xb3, 0x65, 0xaa, 0xb1, 0xfd, 0x0f, 0x99, 0xca, 0x68, 0x43, 0xfe, 0xaf,
	0x8d, 0x31, 0x5c, 0x70, 0xdf, 0x70, 0xbd, 0xa6, 0x3a, 0x06, 0xc8, 0xb9, 0x54, 0x56, 0xa3, 0xda,
	0x56, 0xad, 0x5f, 0xa2, 0x17, 0x70, 0x78, 0x81, 0x39, 0x5a, 0xfd, 0xc6, 0x2e, 0xf6, 0x2d, 0x2c,
	0xda, 0xc9, 0xbb, 0xae, 0xf8, 0xf4, 0xef, 0x14, 0xe6, 0xba, 0xf4, 0x0a, 0xab, 0x6f, 0x22, 0x45,
	0x7a, 0x09, 0xf3, 0xd6, 0x91, 0xd2, 0xa3, 0xa1, 0x03, 0xbe, 0x0b, 0x8f, 0x87, 0xef, 0x9b, 0x5e,
	0xc3, 0xc2, 0xb7, 0x22, 0x5d, 0x76, 0x2a, 0xee, 0x9d, 0x4a, 0xf8, 0x6c, 0x24, 0x43, 0x96, 0x2d,
	0x92, 0x5a, 0xe5, 0x3e, 0x92, 0xb5, 0x73, 0xfb, 0x48, 0x36, 0x9e, 0xfc, 0x04, 0xb0, 0x5d, 0x21,
	0x7d, 0xda, 0xc9, 0xf6, 0xa4, 0x08, 0x8f, 0x06, 0xa2, 0xb2, 0xfc, 0x32, 0x33, 0xff, 0xc1, 0xaf,
	0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xf2, 0x0d, 0xe2, 0x91, 0x05, 0x00, 0x00,
}
