// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

//protoc.exe --proto_path=common/rpcinterface/authinterface --go_out=common/rpcinterface/authinterface --micro_out=common/rpcinterface/authinterface common/rpcinterface/authinterface/auth.proto

package authinterface

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticationReq struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationReq) Reset()         { *m = AuthenticationReq{} }
func (m *AuthenticationReq) String() string { return proto.CompactTextString(m) }
func (*AuthenticationReq) ProtoMessage()    {}
func (*AuthenticationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *AuthenticationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationReq.Unmarshal(m, b)
}
func (m *AuthenticationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationReq.Marshal(b, m, deterministic)
}
func (m *AuthenticationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationReq.Merge(m, src)
}
func (m *AuthenticationReq) XXX_Size() int {
	return xxx_messageInfo_AuthenticationReq.Size(m)
}
func (m *AuthenticationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationReq proto.InternalMessageInfo

func (m *AuthenticationReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type AuthenticationResp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationResp) Reset()         { *m = AuthenticationResp{} }
func (m *AuthenticationResp) String() string { return proto.CompactTextString(m) }
func (*AuthenticationResp) ProtoMessage()    {}
func (*AuthenticationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *AuthenticationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationResp.Unmarshal(m, b)
}
func (m *AuthenticationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationResp.Marshal(b, m, deterministic)
}
func (m *AuthenticationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationResp.Merge(m, src)
}
func (m *AuthenticationResp) XXX_Size() int {
	return xxx_messageInfo_AuthenticationResp.Size(m)
}
func (m *AuthenticationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationResp proto.InternalMessageInfo

func (m *AuthenticationResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthenticationResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AuthorizeReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizeReq) Reset()         { *m = AuthorizeReq{} }
func (m *AuthorizeReq) String() string { return proto.CompactTextString(m) }
func (*AuthorizeReq) ProtoMessage()    {}
func (*AuthorizeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *AuthorizeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizeReq.Unmarshal(m, b)
}
func (m *AuthorizeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizeReq.Marshal(b, m, deterministic)
}
func (m *AuthorizeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizeReq.Merge(m, src)
}
func (m *AuthorizeReq) XXX_Size() int {
	return xxx_messageInfo_AuthorizeReq.Size(m)
}
func (m *AuthorizeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizeReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizeReq proto.InternalMessageInfo

func (m *AuthorizeReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthorizeReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthorizeResp struct {
	Code                 int64               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *AuthorizeResp_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AuthorizeResp) Reset()         { *m = AuthorizeResp{} }
func (m *AuthorizeResp) String() string { return proto.CompactTextString(m) }
func (*AuthorizeResp) ProtoMessage()    {}
func (*AuthorizeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *AuthorizeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizeResp.Unmarshal(m, b)
}
func (m *AuthorizeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizeResp.Marshal(b, m, deterministic)
}
func (m *AuthorizeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizeResp.Merge(m, src)
}
func (m *AuthorizeResp) XXX_Size() int {
	return xxx_messageInfo_AuthorizeResp.Size(m)
}
func (m *AuthorizeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizeResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizeResp proto.InternalMessageInfo

func (m *AuthorizeResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthorizeResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AuthorizeResp) GetData() *AuthorizeResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type AuthorizeResp_Data struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizeResp_Data) Reset()         { *m = AuthorizeResp_Data{} }
func (m *AuthorizeResp_Data) String() string { return proto.CompactTextString(m) }
func (*AuthorizeResp_Data) ProtoMessage()    {}
func (*AuthorizeResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3, 0}
}

func (m *AuthorizeResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizeResp_Data.Unmarshal(m, b)
}
func (m *AuthorizeResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizeResp_Data.Marshal(b, m, deterministic)
}
func (m *AuthorizeResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizeResp_Data.Merge(m, src)
}
func (m *AuthorizeResp_Data) XXX_Size() int {
	return xxx_messageInfo_AuthorizeResp_Data.Size(m)
}
func (m *AuthorizeResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizeResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizeResp_Data proto.InternalMessageInfo

func (m *AuthorizeResp_Data) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type UnAuthorizeReq struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnAuthorizeReq) Reset()         { *m = UnAuthorizeReq{} }
func (m *UnAuthorizeReq) String() string { return proto.CompactTextString(m) }
func (*UnAuthorizeReq) ProtoMessage()    {}
func (*UnAuthorizeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *UnAuthorizeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnAuthorizeReq.Unmarshal(m, b)
}
func (m *UnAuthorizeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnAuthorizeReq.Marshal(b, m, deterministic)
}
func (m *UnAuthorizeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnAuthorizeReq.Merge(m, src)
}
func (m *UnAuthorizeReq) XXX_Size() int {
	return xxx_messageInfo_UnAuthorizeReq.Size(m)
}
func (m *UnAuthorizeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnAuthorizeReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnAuthorizeReq proto.InternalMessageInfo

func (m *UnAuthorizeReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type UnAuthorizeResp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnAuthorizeResp) Reset()         { *m = UnAuthorizeResp{} }
func (m *UnAuthorizeResp) String() string { return proto.CompactTextString(m) }
func (*UnAuthorizeResp) ProtoMessage()    {}
func (*UnAuthorizeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *UnAuthorizeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnAuthorizeResp.Unmarshal(m, b)
}
func (m *UnAuthorizeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnAuthorizeResp.Marshal(b, m, deterministic)
}
func (m *UnAuthorizeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnAuthorizeResp.Merge(m, src)
}
func (m *UnAuthorizeResp) XXX_Size() int {
	return xxx_messageInfo_UnAuthorizeResp.Size(m)
}
func (m *UnAuthorizeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnAuthorizeResp.DiscardUnknown(m)
}

var xxx_messageInfo_UnAuthorizeResp proto.InternalMessageInfo

func (m *UnAuthorizeResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UnAuthorizeResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthenticationReq)(nil), "authinterface.AuthenticationReq")
	proto.RegisterType((*AuthenticationResp)(nil), "authinterface.AuthenticationResp")
	proto.RegisterType((*AuthorizeReq)(nil), "authinterface.AuthorizeReq")
	proto.RegisterType((*AuthorizeResp)(nil), "authinterface.AuthorizeResp")
	proto.RegisterType((*AuthorizeResp_Data)(nil), "authinterface.AuthorizeResp.Data")
	proto.RegisterType((*UnAuthorizeReq)(nil), "authinterface.UnAuthorizeReq")
	proto.RegisterType((*UnAuthorizeResp)(nil), "authinterface.UnAuthorizeResp")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0x54, 0xbe, 0x46, 0x1f, 0x74, 0x43, 0x8b, 0xd8, 0x53, 0x14, 0x7e, 0x94, 0xe6, 0x94, 0x53,
	0x0e, 0x41, 0x3d, 0x23, 0x10, 0xea, 0x89, 0x53, 0xa0, 0x0f, 0x60, 0x9c, 0x85, 0x46, 0xa8, 0x76,
	0x6a, 0x3b, 0x20, 0xf1, 0x30, 0x3c, 0x28, 0x27, 0xe4, 0xa8, 0x44, 0x71, 0x05, 0x2d, 0xbd, 0x79,
	0xb2, 0x3b, 0xb3, 0x3b, 0x93, 0x05, 0x60, 0x8d, 0x59, 0x64, 0xb5, 0x92, 0x46, 0xe2, 0xc8, 0xbe,
	0x2b, 0x61, 0x48, 0x3d, 0x31, 0x4e, 0xc9, 0x14, 0x4e, 0xae, 0x1b, 0xb3, 0x20, 0x61, 0x2a, 0xce,
	0x4c, 0x25, 0x45, 0x41, 0x2b, 0x8c, 0x21, 0x60, 0x9c, 0x93, 0xd6, 0x0f, 0xf2, 0x85, 0x44, 0xe8,
	0xc5, 0x5e, 0x3a, 0x2c, 0xfa, 0x9f, 0x92, 0x1b, 0xc0, 0x4d, 0x9a, 0xae, 0x11, 0xc1, 0xe7, 0xb2,
	0xa4, 0x96, 0x30, 0x28, 0xda, 0x37, 0x86, 0x70, 0xb0, 0x24, 0xad, 0xd9, 0x33, 0x85, 0xff, 0x5a,
	0x9d, 0x6f, 0x98, 0xcc, 0xe0, 0xc8, 0x6a, 0x48, 0x55, 0xbd, 0x93, 0x9d, 0x1a, 0xc1, 0x61, 0xa3,
	0x49, 0x09, 0xb6, 0xa4, 0xf5, 0xc8, 0x0e, 0xdb, 0x5a, 0xcd, 0xb4, 0x7e, 0x93, 0xaa, 0x5c, 0xcb,
	0x74, 0x38, 0xf9, 0xf0, 0x60, 0xd4, 0x13, 0xda, 0x77, 0x0f, 0x9c, 0x82, 0x5f, 0x32, 0xc3, 0xc2,
	0x41, 0xec, 0xa5, 0x41, 0x3e, 0xc9, 0x9c, 0x80, 0x32, 0x47, 0x39, 0xbb, 0x65, 0x86, 0x15, 0x6d,
	0x7b, 0x94, 0x82, 0x6f, 0xd1, 0x1f, 0xc2, 0xca, 0x61, 0x3c, 0x17, 0x8e, 0xd5, 0xdd, 0x9c, 0x2b,
	0x38, 0x76, 0x38, 0xfb, 0xba, 0xca, 0x3f, 0x3d, 0x08, 0x2c, 0xff, 0x9e, 0xd4, 0x6b, 0xc5, 0x09,
	0xe7, 0x30, 0x76, 0xff, 0x18, 0xc6, 0x3f, 0x38, 0x75, 0xee, 0x20, 0x9a, 0xec, 0xe8, 0xd0, 0x35,
	0xce, 0x60, 0xd8, 0x6d, 0x89, 0xa7, 0xbf, 0x67, 0xb7, 0x8a, 0xce, 0xb6, 0x05, 0x8b, 0x77, 0x10,
	0xf4, 0xfc, 0xe2, 0xf9, 0x46, 0xb3, 0x9b, 0x5f, 0x74, 0xb1, 0xad, 0xac, 0xeb, 0xc7, 0xff, 0xed,
	0xad, 0x5f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xff, 0xb1, 0x74, 0xf9, 0x02, 0x00, 0x00,
}
